  name: sync-kiosk
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Sync App Kiosk # 79 char long summary
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.
  confinement: strict
  base: core18
  grade: stable
  
  apps:
    sync-kiosk:
      command: sync_kiosk
      extentions: [flutter-dev]

  parts:
    sync-kiosk:
      plugin: flutter
      source: https://github.com/arndim01/syncappkiosk.git
      flutter-target: lib/main.dart
  
