  name: sync-kiosk
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Sync App Kiosk # 79 char long summary
  description: Sync App Kiosk
  confinement: strict
  base: core18
  grade: stable
  
  parts:
    sync-kiosk:
      plugin: flutter
      source: .
      flutter-target: lib/main.dart

  apps:
    sync-kiosk:
      command: sync_kiosk
      extensions: [flutter-dev]