# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Run flutter test
        run: flutter test
      - name: Build flutter web
        run: flutter build web
      - name: Upload web content
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: web.zip
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./web.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
